In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

# Initialization

In [5]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [6]:
x = tf.constant([[1, 2, 3], [4, 5, 6]], shape=(2, 3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [11]:
x = tf.ones((4, 3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [12]:
x = tf.zeros((3, 2, 5))
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [14]:
x = tf.random.uniform((2, 2), minval=0, maxval=1)
print(x)

tf.Tensor(
[[0.3032378  0.5855876 ]
 [0.3446926  0.28335512]], shape=(2, 2), dtype=float32)


In [16]:
x = tf.random.normal((3, 3), mean=0, stddev=1)
print(x)

tf.Tensor(
[[-0.45119202 -0.19649762 -0.1839145 ]
 [-0.8665618   0.44700778 -0.57600874]
 [-0.00806237 -0.45563033  1.0112574 ]], shape=(3, 3), dtype=float32)


In [17]:
x = tf.range(9)
print(x)



tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [20]:
x = tf.range(start=0, limit=10, delta=1)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [23]:
x = tf.constant(5,shape = (1,1), dtype=tf.float64)
print(x)

x = tf.cast(x, dtype=tf.int32)
print(x)

tf.Tensor([[5.]], shape=(1, 1), dtype=float64)
tf.Tensor([[5]], shape=(1, 1), dtype=int32)


# Mathematical operations

In [24]:
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

In [25]:
z = tf.add(x, y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [26]:
z = tf.subtract(x, y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [27]:
z = x + y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [28]:
z = x - y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [29]:
z = tf.divide(x, y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [30]:
z = tf.multiply(x, y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [31]:
z = x/y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [32]:
z = x*y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [33]:
z = tf.tensordot(x, y, axes=1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [34]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [37]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 2))
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[0.7764083  0.77825755]
 [0.06324717 0.7363217 ]], shape=(2, 2), dtype=float32)


In [38]:
z = x @ y
print(z)

tf.Tensor(
[[0.7764083  0.77825755]
 [0.06324717 0.7363217 ]], shape=(2, 2), dtype=float32)


# Indexing

In [39]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:])
print(x[1:])
print(x[1:3])
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [ ]:
indices = tf.constant([0, 3])
x_indices = tf.gather(x, indices)

In [ ]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])

print(x[0, :])
print(x[0:2, :])


# Reshaping

In [40]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [41]:
x = tf.reshape(x, (3, 3))
print(x)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
